### ISSUE TITLE
ES6 issues

### ISSUE THREAD

**Issue by Beasta** [keitharm/LobabobServer#1]
Initially showed an error that said let and const are currently only allowed in 'Use Strict' mode. I dug into the file and implemented the use strict, but then the parameter default (extra = []) broke it. Both of these are ES2015/ES6 issues.

I'm guessing this is a node version issue. My current nvm version is v5.7.1 which is the stable release and it must not all the fancy new ES6 code.

I'm no npm or nvm pro, but my guess that the best solution would be to just upload a babel transpiled version.

**Comment by keitharm** [comment]
Yeah, I developed the server with 6.2.1 so some new fancy ES6 features are in there that aren't compatible.

Sounds like a good idea to have it pre-transpiled for compatibility with older versions.
